#!/usr/bin/env python
"""
Generate PYTHIA events and save an HDF5 file containing final state particles.
"""
import os
import sys
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--output', '-o', default=None)
parser.add_argument('--events', type=int, default=1000)
parser.add_argument('--random-state', type=int, default=0)
parser.add_argument('--cut-on-pdgid', type=int, default=0)
parser.add_argument('--pdgid-pt-min', type=float, default=-1)
parser.add_argument('--pdgid-pt-max', type=float, default=-1)
parser.add_argument('--params', default=None)
parser.add_argument('-d', '--debug', action='store_true', default=False,       
                    help="show stack trace in the event of "                
                         "an uncaught exception")
parser.add_argument('config')
args = parser.parse_args()

import logging

logging.basicConfig()
log = logging.getLogger(os.path.basename(__file__))
log.setLevel(logging.INFO)

if args.output is None:
    args.output = os.path.splitext(args.config)[0] + '.h5'

if args.params is not None:
    args.params = dict([token.split('=') for token in args.params.split(';')])

from deepjets.generate import generate_events, get_generator_input
from deepjets.samples import create_event_datasets, get_flat_events 
import numpy as np
import h5py

output_exists = os.path.exists(args.output)
h5file = h5py.File(args.output, 'w')
    
try:
    gen_input = get_generator_input('pythia',
        args.config, random_state=args.random_state,
        cut_on_pdgid=args.cut_on_pdgid,
        pdgid_pt_min=args.pdgid_pt_min,
        pdgid_pt_max=args.pdgid_pt_max,
        params_dict=args.params)

    create_event_datasets(h5file, args.events)
    dset_particles = h5file['events']

    ievent = 0
    for event in generate_events(gen_input, args.events):
        dset_particles[ievent] = event
        ievent += 1
except KeyboardInterrupt:
    log.info("Caught Ctrl-c ... cleaning up")
    h5file.close()
    if not output_exists:
        log.info("Removing {0}".format(args.output))
        os.unlink(args.output)
    sys.exit(1)
except Exception as e:
    if args.debug:                        
        # If in debug mode show full stack trace
        import traceback
        traceback.print_exception(*sys.exc_info())
    log.error(str(e))
    h5file.close()
    sys.exit(1)
else:
    h5file.close()
