#!/usr/bin/env python

import os
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--events', type=int, default=1000)
parser.add_argument('--seed', type=int, default=0)
parser.add_argument('--output', '-o', default=None)
parser.add_argument('--jet-size', type=float, default=1.2)
parser.add_argument('--subjet-size-fraction', type=float, default=0.5)
parser.add_argument('--shrink', default=False, action='store_true')
parser.add_argument('--shrink-mass', default='jet')
parser.add_argument('--cut-on-pdgid', type=int, default=0)
parser.add_argument('--pt-min', type=float, default=-1)
parser.add_argument('--pt-max', type=float, default=-1)
parser.add_argument('--params', default=None)
parser.add_argument('config')
args = parser.parse_args()

if args.output is None:
    args.output = os.path.splitext(args.config)[0] + '.h5'

if args.params is not None:
    args.params = dict([token.split('=') for token in args.params.split(';')])

if args.shrink_mass == 'jet':
    # shrink with jet mass
    args.shrink_mass = -1
else:
    args.shrink_mass = float(args.shrink_mass)

from deepjets.generate import generate
from deepjets.utils import mass, tot_mom, pT, dR
import numpy as np
import h5py

DTYPE = np.double

f = h5py.File(args.output, 'w')
dt_jet = np.dtype([('pT', DTYPE), ('eta', DTYPE), ('phi', DTYPE), ('mass', DTYPE)])
dt_jets = h5py.special_dtype(vlen=dt_jet)
dt_constit = h5py.special_dtype(vlen=np.dtype([('ET', DTYPE), ('eta', DTYPE), ('phi', DTYPE)]))

dset_jet = f.create_dataset('jet', (args.events,), dtype=dt_jet)
dset_subjets = f.create_dataset('subjets', (args.events,), dtype=dt_jets)
dset_constit = f.create_dataset('constituents', (args.events,), dtype=dt_constit)
dset_trimmed_constit = f.create_dataset('trimmed_constituents', (args.events,), dtype=dt_constit)
dset_shrinkage = f.create_dataset('shrinkage', (args.events,), dtype=DTYPE)
dset_dr_subjets = f.create_dataset('dR_subjets', (args.events,), dtype=DTYPE)
dset_trimmed_pt = f.create_dataset('trimmed_pT', (args.events,), dtype=DTYPE)
dset_trimmed_mass = f.create_dataset('trimmed_mass', (args.events,), dtype=DTYPE)

# config dsets
dset_jet_size = f.create_dataset('jet_size', (1,), dtype=DTYPE)
dset_subjet_size_fraction = f.create_dataset('subjet_size_fraction', (1,), dtype=DTYPE)

dset_jet_size[0] = args.jet_size
dset_subjet_size_fraction[0] = args.subjet_size_fraction

i = 0
for event in generate(args.config, args.events,
                      random_seed=args.seed,
                      jet_size=args.jet_size,
                      subjet_size_fraction=args.subjet_size_fraction,
                      shrink=args.shrink,
                      shrink_mass=args.shrink_mass,
                      cut_on_pdgid=args.cut_on_pdgid,
                      pt_min=args.pt_min, pt_max=args.pt_max,
                      params_dict=args.params):

    jets, constit, trimmed_constit, shrinkage = event
    
    dset_jet[i] = jets[0]
    dset_subjets[i] = jets[1:]
    dset_constit = constit
    dset_trimmed_constit[i] = trimmed_constit
    dset_shrinkage[i] = shrinkage

    dR_subjets = -1
    if len(jets) >= 3:
        dR_subjets = dR(jets[1], jets[2])
    dset_dr_subjets[i] = dR_subjets
        
    jet_mom_trimmed = tot_mom(trimmed_constit)
    dset_trimmed_pt[i] = pT(*jet_mom_trimmed)
    dset_trimmed_mass[i] = mass(*jet_mom_trimmed)

    i += 1

f.close()
