#!/usr/bin/env python
"""
Generate PYTHIA events in pT bins.
"""
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--events-per-bin', type=int, default=1000)
parser.add_argument('--random-state-offset', type=int, default=0)
parser.add_argument('--pt-min', type=float, default=200)
parser.add_argument('--pt-max', type=float, default=500)
parser.add_argument('--pt-bins', type=float, default=10)
parser.add_argument('--queue', default='long')
parser.add_argument('--dry', action='store_true', default=False)
parser.add_argument('config')
parser.add_argument('output_dir')
args = parser.parse_args()

import os
import subprocess
import numpy as np
from deepjets.path_utils import mkdir_p

args.output_dir = os.path.normpath(args.output_dir)
name = os.path.splitext(os.path.basename(args.config))[0] + '_events'
pt_bin_edges = np.linspace(args.pt_min, args.pt_max, args.pt_bins + 1)
setup_cmd = "cd {0}; source setup.sh;".format(os.path.dirname(os.path.realpath(__file__)))

log_path = os.path.join(args.output_dir, 'log')
print("mkdir -p {0}".format(log_path))
if not args.dry:
    mkdir_p(log_path)

random_state = 1 + args.random_state_offset
for pt_lo, pt_hi in zip(pt_bin_edges[:-1], pt_bin_edges[1:]):
    cmd = (
        'echo "{setup} ./generate {config} --output {output_dir}/{name}_{random_state}_{pt_lo}_{pt_hi}.h5 '
        '--events {events} --random-state {random_state} '
        '--params \\"PhaseSpace:pTHatMin = {pt_lo};PhaseSpace:pTHatMax = {pt_hi}\\"" | '
        'qsub -e {output_dir}/log -o {output_dir}/log -N {name}_{random_state} -l nodes=1:ppn=1 -q {queue};'.format(
            setup=setup_cmd,
            random_state=random_state,
            output_dir=args.output_dir,
            config=args.config,
            pt_lo=int(pt_lo - 20), pt_hi=int(pt_hi + 20),
            queue=args.queue,
            events=args.events_per_bin,
            name=name))
    print(cmd)
    if not args.dry:
        subprocess.call(cmd, shell=True)
    random_state += 1
