#!/usr/bin/env python

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--output', '-o')
parser.add_argument('files', nargs='+')
args = parser.parse_args()

import os
import logging

logging.basicConfig()
log = logging.getLogger(os.path.basename(__file__))
log.setLevel(logging.INFO)

import h5py as h5
import numpy as np

with h5.File(args.output, 'w') as h5output:
    for filename in args.files:
        log.info("merging in file {0} ...".format(filename))
        with h5.File(filename, 'r') as h5input:
            for name, data in h5input.iteritems():
                log.info("merging in dataset {0} with shape {1} ...".format(
                    name, data.shape))
                if len(data) == 0:
                    continue
                #if isinstance(data.dtype, np.object):
                    ## vlen dtype
                    #dtype = h5.special_dtype(vlen=data[0].dtype)
                #else:
                    #dtype = data.dtype
                if name in h5output:
                    # will append to existing dataset in output
                    dset = h5output[name]
                    prev_size = dset.shape[0]
                    dset.resize(prev_size + data.shape[0], axis=0)
                else:
                    # make a new dataset
                    dset = h5output.create_dataset(
                        name, data.shape,
                        maxshape=[None,] + list(data.shape)[1:],
                        dtype=data.dtype)
                    prev_size = 0
                # copy over data
                if data.dtype.name == 'object':
                    for idx, thing in enumerate(data):
                        dset[prev_size + idx] = thing
                else:
                    dset[prev_size:] = data
log.info("done")
