LDFLAGS += -ldl -lboost_iostreams -lboost_thread -lCGAL -lgmp

# deal with pythia
PYTHIADIR   = /usr/local
PYTHIAFLAGS = -I$(PYTHIADIR)/include
PYTHIALIBS  = -L$(PYTHIADIR)/lib/archive -lpythia8

# deal with fastjet
FASTJETINC  =`fastjet-config --cxxflags --plugins`
FASTJETLIB  =`fastjet-config --libs --plugins`

all:
	g++ -o WprimeJetGen WprimeJetGen.cc \
		$(PYTHIAFLAGS) $(PYTHIALIBS) \
		$(FASTJETINC) $(FASTJETLIB) \
		$(LDFLAGS)
