#!/usr/bin/env python


def plot(input):
    import os
    import numpy as np
    from deepjets import generate
    from deepjets.preprocessing import preprocess
    from deepjets.utils import plot_jet_image, jet_mass
    from matplotlib import pyplot as plt
    import h5py
    
    h5file = h5py.File(input, 'r')
    dset_images = h5file['images']
    weights = None
    if 'auxvars' in h5file:
        auxvars = h5file['auxvars']
        if 'weights' in auxvars.dtype.names:
            weights = auxvars['weights']
    output_prefix = os.path.splitext(input)[0]
    
    if weights is not None:
        print("plotting weighted average image {0} ...".format(input))
    else:
        print("plotting average image {0} ...".format(input))

    # plot jet images
    fig = plt.figure(figsize=(6, 5))
    ax = fig.add_subplot(111)
    avg_image = np.average(dset_images[:], weights=weights, axis=0)
    plot_jet_image(ax, avg_image, vmax=1e-2)
    fig.tight_layout()
    fig.savefig(output_prefix + '.png')


if __name__ == '__main__':
    from argparse import ArgumentParser

    parser = ArgumentParser()
    parser.add_argument('-n', '--jobs', type=int, default=-1)
    parser.add_argument('files', nargs='+')
    args = parser.parse_args()

    from deepjets.parallel import map_pool, FuncWorker

    map_pool(
        FuncWorker, [(plot, filename) for filename in args.files],
        n_jobs=args.jobs)
