#!/usr/bin/env python

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--sig', dest='signal_file')
parser.add_argument('--bkg', dest='background_file')
parser.add_argument('--events', type=int, default=-1)
parser.add_argument('--epochs', type=int, default=50)
parser.add_argument('--max-iter', type=int, default=20)
parser.add_argument('--name')
parser.add_argument('--nfolds', type=int, default=1)
parser.add_argument('--test-fraction', type=float, default=0.2)
parser.add_argument('--val-fraction', type=float, default=0.1)
args = parser.parse_args()

from deepjets.utils import prepare_datasets
from deepjets.path_utils import mkdir_p
from deepjets.bayesopt import bayesian_optimization

mkdir_p('datasets')
mkdir_p('models')

dataset_name = 'datasets/' + args.name
model_name = 'models/' + args.name

# Prepare datasets once for all trainings
h5_files = prepare_datasets(
    args.signal_file, args.background_file, dataset_name,
    test_frac=args.test_fraction, val_frac=0, # use Keras' internal val_frac
    n_folds=args.nfolds,
    shuffle=True, balance=True,
    n_sig=args.events, n_bkd=args.events)

bayesian_optimization(
    model_name, h5_files['train'], max_iter=args.max_iter,
    epochs=args.epochs, val_frac=args.val_fraction)
