#!/usr/bin/env python

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--bins', default=100, type=int)
parser.add_argument('--output', '-o', default='plots.png')
parser.add_argument('--mass-min', type=float, default=50.)
parser.add_argument('--mass-max', type=float, default=110.)
parser.add_argument('--pt-min', type=float, default=150.)
parser.add_argument('--pt-max', type=float, default=550.)
parser.add_argument('signal')
parser.add_argument('background')
args = parser.parse_args()

from deepjets.plotting import plot_kinematics

fig = plot_kinematics(
    args.signal, args.background,
    nbins=args.bins,
    mass_range=(args.mass_min, args.mass_max),
    pt_range=(args.pt_min, args.pt_max))
fig.savefig(args.output)
